-- MySQL Script generated by MySQL Workbench
-- Mon Nov 18 23:27:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `rating` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `age` TINYINT NOT NULL,
  `gender` VARCHAR(2) NOT NULL,
  `height` SMALLINT NOT NULL,
  `weight` TINYINT NOT NULL,
  `school` VARCHAR(45) NOT NULL,
  `latitude` DECIMAL(18,10) NULL,
  `longitude` DECIMAL(18,10) NULL,
  `balance` VARCHAR(45) NULL,
  `preference` VARCHAR(45) NULL,
  `intense` VARCHAR(45) NULL,
  `frequency` TINYINT NULL,
  `place` VARCHAR(45) NULL,
  `friend` TINYINT NULL,
  `goal` VARCHAR(45) NULL,
  `method` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`facility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`facility` (
  `faciliy_id` INT NOT NULL AUTO_INCREMENT,
  `facility_name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `sportcol` VARCHAR(45) NULL,
  `exercise` VARCHAR(45) NULL,
  `facilitycol` VARCHAR(45) NULL,
  `latitude` DECIMAL(18,10) NULL,
  `longitude` DECIMAL(18,10) NULL,
  PRIMARY KEY (`faciliy_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`program`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`program` (
  `program_id` INT NOT NULL AUTO_INCREMENT,
  `facility_id` INT NOT NULL,
  `program_name` VARCHAR(45) NULL,
  `programcol` VARCHAR(45) NULL,
  `begin` VARCHAR(45) NULL,
  `end` VARCHAR(45) NULL,
  `day` VARCHAR(45) NULL,
  `time` VARCHAR(45) NULL,
  `recruit` TINYINT NULL,
  `price` INT NULL,
  PRIMARY KEY (`program_id`),
  INDEX `fk_sport_facility_idx` (`facility_id` ASC) VISIBLE,
  CONSTRAINT `fk_sport_facility`
    FOREIGN KEY (`facility_id`)
    REFERENCES `mydb`.`facility` (`faciliy_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`class` (
  `user_user_id` INT NOT NULL,
  `program_program_id` INT NOT NULL,
  `select` TINYINT NULL,
  `favorit` TINYINT NULL,
  PRIMARY KEY (`user_user_id`, `program_program_id`),
  INDEX `fk_user_has_program_program1_idx` (`program_program_id` ASC) VISIBLE,
  INDEX `fk_user_has_program_user1_idx` (`user_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_program_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_program_program1`
    FOREIGN KEY (`program_program_id`)
    REFERENCES `mydb`.`program` (`program_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
